<a href="https://colab.research.google.com/github/MarkeyBass/pytorch-play/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSOR MATH OPERATIONS
* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shorthand and uh, Longhand
* Reassignment




In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Subtraction
tensor_b - tensor_a

tensor([-4, -4, -4, -4])

In [8]:
# Subtraction Longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
# Multiply Longhand
torch.mul(tensor_b, tensor_a)

tensor([ 5, 12, 21, 32])

In [10]:
# Divide Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [18]:
# Modulus Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [20]:
# Exponents / Power
pow_1 = torch.pow(tensor_a, tensor_b)
pow_2 = tensor_a ** tensor_b

pow_1, pow_2

(tensor([    1,    64,  2187, 65536]), tensor([    1,    64,  2187, 65536]))