<a href="https://colab.research.google.com/github/MarkeyBass/pytorch-play/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
my_list = [[1,2,3,4,5], [1,2,3,4,5]]
my_list

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.85804879, 0.8255285 , 0.42828924, 0.74723726],
       [0.32827843, 0.04465698, 0.38355367, 0.9791398 ],
       [0.99506944, 0.17395477, 0.70647133, 0.24113418]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.1240, -0.1569,  0.9556, -0.6563],
        [-0.1209,  0.3024,  0.6979, -0.3631],
        [ 0.4789,  0.2416, -1.7852,  2.5896]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8580, 0.8255, 0.4283, 0.7472],
        [0.3283, 0.0447, 0.3836, 0.9791],
        [0.9951, 0.1740, 0.7065, 0.2411]], dtype=torch.float64)